---
- name: create a user and file 
  hosts: all
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create a file
      file:
        name: "{{d}}"
        state: "{{e}}"
