---
- name: implementing hosts scope varibles
  hosts: 172.31.40.67
  tasks:
    - name: create a user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        shell: "{{e}}"
        comment: "{{f}}"
...
